### ISSUE TITLE
Create the data combining SDS/ISL/Road absence/Distance to road

### ISSUE THREAD

**Issue by qszhao** [urbanbigdatacentre/ideamaps-models#101]
We will prepare SDS/ISL/Road absence dataset for generating training datasets.

**Comment by andymithamclarke** [comment]
SDS + ISL have been combined 

Road Metrics - density + absence + distance == the approach has not been decided

@qszhao has requested that Monika - Ryan and Dana provide opinions on how to combine these metrics.

Current main blockers:
- How to estimate the road width because the data has a lot of missing values here
- Different types of roads - whether to include or not.

@diegopajarito suggesting that road width gets discarded because of lack of values.

For now as of 24th Sept - Ryan suggested that @manuellacomerio read some papers that he has sent through - @qszhao - please confirm this - and be aware of time implications in delaying progress with this :)

**Comment by qszhao** [comment]
I just replied to Ryan's email, and I think we can take his approach to generate the road width for our study. It is only two papers to read so I don't believe it is a bit issue here.

**Comment by qszhao** [comment]
From the conversation with Ryan, the road width will take more time to generate, based on each city with human efforts. in this case, we will park the road width for now and proceed with distance to road and road existence/absence. @andymithamclarke @manuellacomerio

**Comment by andymithamclarke** [comment]
Complete today:

- Joining all the datasets - SDS + IL + Reference data + PAR Validation data
- Calculated absence and presence of roads

Still Outstanding:
- Calculate Distance to roads

**Comment by andymithamclarke** [comment]
Decision to remove road density made @qszhao @joaoporto @manuellacomerio

**Comment by andymithamclarke** [comment]
Closing with the idea of opening new issues in this sprint 4.
