### ISSUE TITLE
Review Reference Data

### ISSUE THREAD

**Issue by andymithamclarke** [urbanbigdatacentre/ideamaps-models#44]
@Gtregon to review the reference data created by @Adenikemie and @AlexandraMiddleton in #9 .

This issue can be closed when the quality check has been complete - comments added into the document.

**Comment by gielinkg** [comment]
@Gtregon update here plz

**Comment by Gtregon** [comment]
✅ Definition of Done

- [x] 1. Define acceptance criteria.
The data from the validation activities will be used by @Adenikemie and @AlexandraMiddleton to validate model outputs and produce new reference data. The outputs from this task can also be used to feed into the confidence scores that will be generated in phase 2.2.
- [x] 2. Assess the need for a review process. If a review process is required, the issue states:
      i. Who is involved in the review? @Gtregon 
      ii. When will the review take place? Review has been conducted remotely and the gpkg's have been reviewed.
      iii. Who is responsible for taking on the feedback? @Adenikemie @AlexandraMiddleton 
      iv. What additional tasks are involved and are they visible on the backlog? 
- [ ]  3. Make progress and post updates. NA
- [x]  4. Check off completed acceptance criteria.
- []  5. Post links to digital outputs. NA
- [x]  6. Note the value added to the product.
The data will be used directly in the modelling process of the morphological informality model being developed in phase 2.1 and has been used to validate previous model outputs (from phase 1). The data can also be used to generate confidence scores of model outputs which will be integrated in the interface during phase 2.2 or phase 3. 

Additional feedback for @AlexandraMiddleton and @Adenikemie : Thanks very much for your work both! You have produced some great outputs. The only thing that needs doing is to rename the gpkg's so that they align/match with one another i.e. atm, we have multiple file names for different cities (slum ref 1st round, kano slum ref, aiverified not slum etc. It would be great if we can have the same names for all our cities and file names. I will create another issue for this and we can schedule a meeting now that Adenike is back from AL and figure out next steps. Thanks again!
