### ISSUE TITLE
Gather Healthcare Access Data

### ISSUE THREAD

**Issue by andymithamclarke** [urbanbigdatacentre/ideamaps-models#45]
### ✅ Definition of Done
---

- [x] 1. Define acceptance criteria.
- [x] 2. Assess the need for a review process. If a review process is required, the issue states:
    1. Who is involved in the review?
    2. When will the review take place?
    3. Who is responsible for taking on the feedback?
    4. What additional tasks are involved and are they visible on the backlog?
- [x] 3. Make progress and post updates.
- [x] 4. Check off completed acceptance criteria.
- [ ] 5. Post links to digital outputs.
- [ ] 6. Note the value added to the product.

**Comment by andymithamclarke** [comment]
We need to gather the datasets from existing repositories associated with IDEAMAPS + External Sources related to the development.

The criteria is: 
- covers Kano
- fulfils the need of the modeling approach @diegopajarito to define this further.

All of the datasets need to be validated according to the above criteria by @qszhao Sabitu and Taiwo.

**Comment by qszhao** [comment]
It's great to see this one and thanks Andy. This can be a good task for the new MSc RA to work on. In terms of the spatial accessibility methods, we can use packages such as the PySAL Access package: https://pysal.org/access/

**Comment by gielinkg** [comment]
Once @diegopajarito has checked and gathered the data from IDEAMAPS data library and OSM database, the output will be a draft of the Data section of the model specification. Once @diegopajarito  has a draft it should be posted here and shared with Qunshan, Sabitu, and Taiwo.

**Comment by gielinkg** [comment]
Link for data: https://docs.google.com/spreadsheets/d/1tAB9mB-lXVwV1qvUxQSjzkH0JFH1-qSF9rl6a4Z_xAg/edit?usp=sharing

**Comment by diegopajarito** [comment]
Information available was gathered and the OSM Files were confirmed to be available in CRIB. Additional datasets were analysed by reading the data repository spreadsheet but none of them were made available since they were not considered relevant for the modelling task (Accessibility to health care)

Diego emailed the domain experts sharing the findings and asking them to reflect on potential data sources and additional definitions / facilities to map for health care. 

The issue is closed after procuring the data available to this date and communicating the initial findings. This initial review unlocks the model definition planned for this sprint. (value added)

Note that the template to document the model was not updated due to the limitations encountered when reviewing the data.
